IF
  Global("FW1400Reveal_Ankheg Farms","Global",0)
  GlobalGT("Chapter","Global",2)
THEN
  RESPONSE #100
    RevealAreaOnMap("FW1400")
    SetGlobal("FW1400Reveal_Ankheg Farms","Global",1)
    Continue()
END

IF
  Global("FW2400Reveal_Peldvale","Global",0)
  GlobalGT("Chapter","Global",2)
THEN
  RESPONSE #100
    RevealAreaOnMap("FW2400")
    SetGlobal("FW2400Reveal_Peldvale","Global",1)
    Continue()
END
