ACTION_DEFINE_ASSOCIATIVE_ARRAY areas BEGIN
  ar5500 => 1
  ar6000 => 1
  ar6100 => 1
END

ACTION_FOR_EACH node IN 0 1 2 3 BEGIN
  ACTION_PHP_EACH "fl#INDEX_%node%" AS e => _ BEGIN
    OUTER_SPRINT src "%e_0%"
    OUTER_SPRINT target "%e_1%"
    OUTER_SPRINT cmp "%src%"
    ACTION_TO_LOWER cmp
    ACTION_IF VARIABLE_IS_SET $areas("%cmp%") BEGIN
      OUTER_SPRINT $fl#ENC1("%src%" "%node%" "%target%") "l-ar01"
      OUTER_SET $fl#PROB("%src%" "%node%" "%target%") = 33
    END
  END
END
