IF
  Global("AR7100Reveal_High Hedge","Global",0)
  GlobalGT("Chapter","Global",2)
THEN
  RESPONSE #100
    RevealAreaOnMap("AR7100")
    SetGlobal("AR7100Reveal_High Hedge","Global",1)
    Continue()
END

IF
  Global("AR9600Reveal_Red Canyons","Global",0)
  GlobalGT("Chapter","Global",2)
THEN
  RESPONSE #100
    RevealAreaOnMap("AR9600")
    SetGlobal("AR9600Reveal_Red Canyons","Global",1)
    Continue()
END
