IF
  Global("AR3400Reveal_Firewine Bridge","Global",0)
  GlobalGT("Chapter","Global",3)
THEN
  RESPONSE #100
    RevealAreaOnMap("AR3400")
    SetGlobal("AR3400Reveal_Firewine Bridge","Global",1)
    Continue()
END

IF
  Global("AR4600Reveal_Dragon's Run","Global",0)
  GlobalGT("Chapter","Global",3)
THEN
  RESPONSE #100
    RevealAreaOnMap("AR4600")
    SetGlobal("AR4600Reveal_Dragon's Run","Global",1)
    Continue()
END
