IF
  Global("AR4200Reveal_Western Cloudpeaks","Global",0)
  GlobalGT("Chapter","Global",2)
THEN
  RESPONSE #100
    RevealAreaOnMap("AR4200")
    SetGlobal("AR4200Reveal_Western Cloudpeaks","Global",1)
    Continue()
END

IF
  Global("AR4400Reveal_Nashkel Mines","Global",0)
  GlobalLT("Chapter","Global",3)
THEN
  RESPONSE #100
    RevealAreaOnMap("AR4400")
    SetGlobal("AR4400Reveal_Nashkel Mines","Global",1)
    Continue()
END
