IF
  Global("HelpBjornin","Global",2)
  Global("AR3100Reveal_Wilderness Lake","Global",0)
THEN
  RESPONSE #100
    RevealAreaOnMap("AR3100")
    SetGlobal("AR3100Reveal_Wilderness Lake","Global",1)
    Continue()
END

IF
  Global("HelpGurke","GLOBAL",1)
  !PartyHasItem("CLCK06") // Cloak of Non-Detection
  Global("AR7000Reveal_Cloakwood Lodge","Global",0)
THEN
  RESPONSE #100
    RevealAreaOnMap("AR7000")
    SetGlobal("AR7000Reveal_Cloakwood Lodge","Global",1)
    Continue()
END
