IF
  Global("FW5200Reveal_Western Cloudpeaks","Global",0)
  GlobalGT("Chapter","Global",1)
THEN
  RESPONSE #100
    RevealAreaOnMap("FW5200")
    SetGlobal("FW5200Reveal_Western Cloudpeaks","Global",1)
    Continue()
END

IF
  Global("FW5400Reveal_Nashkel Mines","Global",0)
  GlobalLT("Chapter","Global",2)
THEN
  RESPONSE #100
    RevealAreaOnMap("FW5400")
    SetGlobal("FW5400Reveal_Nashkel Mines","Global",1)
    Continue()
END
