IF
  Global("FW4500Reveal_Firewine Bridge","Global",0)
  GlobalGT("Chapter","Global",2)
THEN
  RESPONSE #100
    RevealAreaOnMap("FW4500")
    SetGlobal("FW4500Reveal_Firewine Bridge","Global",1)
    Continue()
END

IF
  Global("FW5500Reveal_Dragon's Run","Global",0)
  GlobalGT("Chapter","Global",2)
THEN
  RESPONSE #100
    RevealAreaOnMap("FW5500")
    SetGlobal("FW5500Reveal_Dragon's Run","Global",1)
    Continue()
END
